version: "3.4"

services:
  php:
    build:
      context: ./api
      target: savart_php_dev
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - jwt_certs:/srv/app/config/jwt
      - ./api:/srv/app
      - ./api/docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${XDEBUG_CONFIG:-}"
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  caddy:
    build:
      context: api/
      target: savart_caddy
    depends_on:
      - php
    environment:
      SERVER_NAME: ${SERVER_NAME}:80
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
      - ./api/public:/srv/app/public:ro
      - ./api/docker/caddy/default/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'savart'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    command: mysqld --sql_mode="STRICT_TRANS_TABLES"

volumes:
  php_socket:
  caddy_data:
  caddy_config:
  mysql_data:
  jwt_certs:
